// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests
{
    /// <summary>
    /// Builds and executes requests for operations under \algorithm\v1\cancel\{algorithmName}\requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaPosts.Client.algorithm.v1.cancel.item.requests.item collection</summary>
        /// <param name="position">Request identifier</param>
        /// <returns>A <see cref="global::KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests.Item.WithRequestItemRequestBuilder"/></returns>
        public global::KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests.Item.WithRequestItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("requestId", position);
                return new global::KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests.Item.WithRequestItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests.RequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/cancel/{algorithmName}/requests", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Cancel.Item.Requests.RequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RequestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/cancel/{algorithmName}/requests", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
