// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Models.V1;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckpointedRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The algorithm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Algorithm { get; set; }
#nullable restore
#else
        public string Algorithm { get; set; }
#endif
        /// <summary>The algorithm_failure_cause property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlgorithmFailureCause { get; set; }
#nullable restore
#else
        public string AlgorithmFailureCause { get; set; }
#endif
        /// <summary>The algorithm_failure_details property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlgorithmFailureDetails { get; set; }
#nullable restore
#else
        public string AlgorithmFailureDetails { get; set; }
#endif
        /// <summary>The api_version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiVersion { get; set; }
#nullable restore
#else
        public string ApiVersion { get; set; }
#endif
        /// <summary>The applied_configuration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec? AppliedConfiguration { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec AppliedConfiguration { get; set; }
#endif
        /// <summary>The configuration_overrides property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec? ConfigurationOverrides { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec ConfigurationOverrides { get; set; }
#endif
        /// <summary>The content_hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentHash { get; set; }
#nullable restore
#else
        public string ContentHash { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The job_uid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobUid { get; set; }
#nullable restore
#else
        public string JobUid { get; set; }
#endif
        /// <summary>The last_modified property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModified { get; set; }
#nullable restore
#else
        public string LastModified { get; set; }
#endif
        /// <summary>The lifecycle_stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LifecycleStage { get; set; }
#nullable restore
#else
        public string LifecycleStage { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.Models.AlgorithmRequestRef? Parent { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.Models.AlgorithmRequestRef Parent { get; set; }
#endif
        /// <summary>The payload_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayloadUri { get; set; }
#nullable restore
#else
        public string PayloadUri { get; set; }
#endif
        /// <summary>The payload_valid_for property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayloadValidFor { get; set; }
#nullable restore
#else
        public string PayloadValidFor { get; set; }
#endif
        /// <summary>The received_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceivedAt { get; set; }
#nullable restore
#else
        public string ReceivedAt { get; set; }
#endif
        /// <summary>The received_by_host property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceivedByHost { get; set; }
#nullable restore
#else
        public string ReceivedByHost { get; set; }
#endif
        /// <summary>The result_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultUri { get; set; }
#nullable restore
#else
        public string ResultUri { get; set; }
#endif
        /// <summary>The sent_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SentAt { get; set; }
#nullable restore
#else
        public string SentAt { get; set; }
#endif
        /// <summary>The tag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.Models.CheckpointedRequest"/> and sets the default values.
        /// </summary>
        public CheckpointedRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.Models.CheckpointedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.Models.CheckpointedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.Models.CheckpointedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "algorithm", n => { Algorithm = n.GetStringValue(); } },
                { "algorithm_failure_cause", n => { AlgorithmFailureCause = n.GetStringValue(); } },
                { "algorithm_failure_details", n => { AlgorithmFailureDetails = n.GetStringValue(); } },
                { "api_version", n => { ApiVersion = n.GetStringValue(); } },
                { "applied_configuration", n => { AppliedConfiguration = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec.CreateFromDiscriminatorValue); } },
                { "configuration_overrides", n => { ConfigurationOverrides = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec.CreateFromDiscriminatorValue); } },
                { "content_hash", n => { ContentHash = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "job_uid", n => { JobUid = n.GetStringValue(); } },
                { "last_modified", n => { LastModified = n.GetStringValue(); } },
                { "lifecycle_stage", n => { LifecycleStage = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::KiotaPosts.Client.Models.Models.AlgorithmRequestRef>(global::KiotaPosts.Client.Models.Models.AlgorithmRequestRef.CreateFromDiscriminatorValue); } },
                { "payload_uri", n => { PayloadUri = n.GetStringValue(); } },
                { "payload_valid_for", n => { PayloadValidFor = n.GetStringValue(); } },
                { "received_at", n => { ReceivedAt = n.GetStringValue(); } },
                { "received_by_host", n => { ReceivedByHost = n.GetStringValue(); } },
                { "result_uri", n => { ResultUri = n.GetStringValue(); } },
                { "sent_at", n => { SentAt = n.GetStringValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("algorithm", Algorithm);
            writer.WriteStringValue("algorithm_failure_cause", AlgorithmFailureCause);
            writer.WriteStringValue("algorithm_failure_details", AlgorithmFailureDetails);
            writer.WriteStringValue("api_version", ApiVersion);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec>("applied_configuration", AppliedConfiguration);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec>("configuration_overrides", ConfigurationOverrides);
            writer.WriteStringValue("content_hash", ContentHash);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("job_uid", JobUid);
            writer.WriteStringValue("last_modified", LastModified);
            writer.WriteStringValue("lifecycle_stage", LifecycleStage);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.Models.AlgorithmRequestRef>("parent", Parent);
            writer.WriteStringValue("payload_uri", PayloadUri);
            writer.WriteStringValue("payload_valid_for", PayloadValidFor);
            writer.WriteStringValue("received_at", ReceivedAt);
            writer.WriteStringValue("received_by_host", ReceivedByHost);
            writer.WriteStringValue("result_uri", ResultUri);
            writer.WriteStringValue("sent_at", SentAt);
            writer.WriteStringValue("tag", Tag);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
