// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Algorithm.V1;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Algorithm
{
    /// <summary>
    /// Builds and executes requests for operations under \algorithm
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AlgorithmRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The v1 property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.V1RequestBuilder V1
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.AlgorithmRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AlgorithmRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.AlgorithmRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AlgorithmRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
