// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models.Resource
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Quantity_Format
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DecimalExponent")]
        #pragma warning disable CS1591
        DecimalExponent,
        #pragma warning restore CS1591
        [EnumMember(Value = "BinarySI")]
        #pragma warning disable CS1591
        BinarySI,
        #pragma warning restore CS1591
        [EnumMember(Value = "DecimalSI")]
        #pragma warning disable CS1591
        DecimalSI,
        #pragma warning restore CS1591
    }
}
