// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Algorithm.V1.BufferNamespace;
using KiotaPosts.Client.Algorithm.V1.Cancel;
using KiotaPosts.Client.Algorithm.V1.Metadata;
using KiotaPosts.Client.Algorithm.V1.Payload;
using KiotaPosts.Client.Algorithm.V1.Results;
using KiotaPosts.Client.Algorithm.V1.Run;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Algorithm.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \algorithm\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The buffer property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.BufferNamespace.BufferRequestBuilder Buffer
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.BufferNamespace.BufferRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cancel property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metadata property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.Metadata.MetadataRequestBuilder Metadata
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.Metadata.MetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payload property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.Payload.PayloadRequestBuilder Payload
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.Payload.PayloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The results property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.Results.ResultsRequestBuilder Results
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.Results.ResultsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.Run.RunRequestBuilder Run
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.Run.RunRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
