apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla
          ports:
            - containerPort: 9042
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - '[ "$(nodetool statusgossip)" = "running" ]'
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scylla-service
spec:
  selector:
    app: scylla
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
  type: ClusterIP