// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Algorithm.V1.Run.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Algorithm.V1.Run
{
    /// <summary>
    /// Builds and executes requests for operations under \algorithm\v1\run
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaPosts.Client.algorithm.v1.run.item collection</summary>
        /// <param name="position">Algorithm name</param>
        /// <returns>A <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder"/></returns>
        public global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("algorithmName", position);
                return new global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.RunRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/run", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.RunRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/run", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
