// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Algorithm.V1.Metadata.Item.Requests;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Algorithm.V1.Metadata.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \algorithm\v1\metadata\{algorithmName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAlgorithmNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The requests property</summary>
        public global::KiotaPosts.Client.Algorithm.V1.Metadata.Item.Requests.RequestsRequestBuilder Requests
        {
            get => new global::KiotaPosts.Client.Algorithm.V1.Metadata.Item.Requests.RequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Metadata.Item.WithAlgorithmNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAlgorithmNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/metadata/{algorithmName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Metadata.Item.WithAlgorithmNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAlgorithmNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/metadata/{algorithmName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
