// <auto-generated/>
#pragma warning disable CS0618
using KiotaPosts.Client.Models.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.Algorithm.V1.Run.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \algorithm\v1\run\{algorithmName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAlgorithmNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAlgorithmNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/run/{algorithmName}{?dryRun*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAlgorithmNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/algorithm/v1/run/{algorithmName}{?dryRun*}", rawUrl)
        {
        }
        /// <summary>
        /// Accepts an algorithm payload and places it into a scheduling queue
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNamePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNamePostResponse?> PostAsWithAlgorithmNamePostResponseAsync(global::KiotaPosts.Client.Models.Models.AlgorithmRequest body, Action<RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNamePostResponse> PostAsWithAlgorithmNamePostResponseAsync(global::KiotaPosts.Client.Models.Models.AlgorithmRequest body, Action<RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNamePostResponse>(requestInfo, global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNamePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Accepts an algorithm payload and places it into a scheduling queue
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsWithAlgorithmNamePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameResponse?> PostAsync(global::KiotaPosts.Client.Models.Models.AlgorithmRequest body, Action<RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameResponse> PostAsync(global::KiotaPosts.Client.Models.Models.AlgorithmRequest body, Action<RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameResponse>(requestInfo, global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Accepts an algorithm payload and places it into a scheduling queue
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::KiotaPosts.Client.Models.Models.AlgorithmRequest body, Action<RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::KiotaPosts.Client.Models.Models.AlgorithmRequest body, Action<RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Accepts an algorithm payload and places it into a scheduling queue
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAlgorithmNameItemRequestBuilderPostQueryParameters 
        {
            /// <summary>If false, will buffer but not submit to the target cluster</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("dryRun")]
            public string? DryRun { get; set; }
#nullable restore
#else
            [QueryParameter("dryRun")]
            public string DryRun { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithAlgorithmNameItemRequestBuilderPostRequestConfiguration : RequestConfiguration<global::KiotaPosts.Client.Algorithm.V1.Run.Item.WithAlgorithmNameItemRequestBuilder.WithAlgorithmNameItemRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
