apiVersion: science.sneaksanddata.com/v1
kind: NexusAlgorithmTemplate
metadata:
  name: hello-world
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  args:
    - main.py
    - '--sas-uri=%s'
    - '--request-id=%s'
  command: python
  computeResources:
    cpuLimit: 1000m
    memoryLimit: 1000Mi
  container:
    image: nexus-hello
    registry: ghcr.io/sneaksanddata
    serviceAccountName: nexus
    versionTag: 0.1.2-4-g181d908
  datadogIntegrationSettings:
    mountDatadogSocket: true
  errorHandlingBehaviour:
    fatalExitCodes:
      - 137
    transientExitCodes:
      - 139
  runtimeEnvironment:
    deadlineSeconds: 120
    environmentVariables:
      - name: DD_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: NEXUS__CLIENT__SCHEDULER
        value: http://nexus.default.svc.cluster.local:8080
      - name: NEXUS__CLIENT__SCHEDULER_ACCESS_TOKEN
        value: ""
      - name: NEXUS__CLIENT__RECEIVER
        value: http://nexus-receiver.default.svc.cluster.local:8080
      - name: PROTEUS__AWS_REGION
        value: us-east-1
      - name: PROTEUS__AWS_ENDPOINT
        value: http://minio.default.svc.cluster.local:9000
      - name: PROTEUS__AWS_SECRET_ACCESS_KEY
        value: minioadmin
      - name: PROTEUS__AWS_ACCESS_KEY_ID
        value: minioadmin
      - name: NEXUS__METRICS__PROVIDER
        value: adapta.metrics.providers.void_provider.VoidMetricsProvider
      - name: NEXUS__RESULT__STORAGE_CLIENT_CLASS
        value: adapta.storage.blob.s3_storage_client.S3StorageClient
      - name: NEXUS__RESULT__OUTPUT_PATH
        value: s3a://nexus-sdk-tests
      - name: NEXUS__REMOTE_ALGORITHM__COMPRESSION_IMPORT_PATH
        value: ""
      - name: NEXUS__REMOTE_ALGORITHM__DECOMPRESSION_IMPORT_PATH
        value: ""
      - name: NEXUS__INPUTS__QUERY_ENABLED_STORE__CONNECTION_STRING
        value: ""
      - name: NEXUS__THREADING__BLOCKING_POOL_MAX_SIZE
        value: '10'
      - name: NEXUS__LOGGING__DATADOG__ENABLED
        value: '0'
      - name: NEXUS__LOGGING__FIXED_TEMPLATE
        value: ''
    mappedEnvironmentVariables: []
    maximumRetries: 1
  workgroupRef:
    group: science.sneaksanddata.com
    kind: NexusAlgorithmWorkgroup
    name: default
