// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnvFromSource : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ConfigMap to select from+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.ConfigMapEnvSource? ConfigMapRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.ConfigMapEnvSource ConfigMapRef { get; set; }
#endif
        /// <summary>Optional text to prepend to the name of each environment variable. Must be a C_IDENTIFIER.+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prefix { get; set; }
#nullable restore
#else
        public string Prefix { get; set; }
#endif
        /// <summary>The Secret to select from+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.SecretEnvSource? SecretRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.SecretEnvSource SecretRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.V1.EnvFromSource"/> and sets the default values.
        /// </summary>
        public EnvFromSource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.V1.EnvFromSource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.V1.EnvFromSource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.V1.EnvFromSource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configMapRef", n => { ConfigMapRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.ConfigMapEnvSource>(global::KiotaPosts.Client.Models.V1.ConfigMapEnvSource.CreateFromDiscriminatorValue); } },
                { "prefix", n => { Prefix = n.GetStringValue(); } },
                { "secretRef", n => { SecretRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.SecretEnvSource>(global::KiotaPosts.Client.Models.V1.SecretEnvSource.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.ConfigMapEnvSource>("configMapRef", ConfigMapRef);
            writer.WriteStringValue("prefix", Prefix);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.SecretEnvSource>("secretRef", SecretRef);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
