// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnvVarSource : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Selects a key of a ConfigMap.+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.ConfigMapKeySelector? ConfigMapKeyRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.ConfigMapKeySelector ConfigMapKeyRef { get; set; }
#endif
        /// <summary>Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels[&apos;&lt;KEY&gt;&apos;]`, `metadata.annotations[&apos;&lt;KEY&gt;&apos;]`,spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.ObjectFieldSelector? FieldRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.ObjectFieldSelector FieldRef { get; set; }
#endif
        /// <summary>Selects a resource of the container: only resources limits and requests(limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.ResourceFieldSelector? ResourceFieldRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.ResourceFieldSelector ResourceFieldRef { get; set; }
#endif
        /// <summary>Selects a key of a secret in the pod&apos;s namespace+optional</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.SecretKeySelector? SecretKeyRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.SecretKeySelector SecretKeyRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.V1.EnvVarSource"/> and sets the default values.
        /// </summary>
        public EnvVarSource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.V1.EnvVarSource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.V1.EnvVarSource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.V1.EnvVarSource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configMapKeyRef", n => { ConfigMapKeyRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.ConfigMapKeySelector>(global::KiotaPosts.Client.Models.V1.ConfigMapKeySelector.CreateFromDiscriminatorValue); } },
                { "fieldRef", n => { FieldRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.ObjectFieldSelector>(global::KiotaPosts.Client.Models.V1.ObjectFieldSelector.CreateFromDiscriminatorValue); } },
                { "resourceFieldRef", n => { ResourceFieldRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.ResourceFieldSelector>(global::KiotaPosts.Client.Models.V1.ResourceFieldSelector.CreateFromDiscriminatorValue); } },
                { "secretKeyRef", n => { SecretKeyRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.SecretKeySelector>(global::KiotaPosts.Client.Models.V1.SecretKeySelector.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.ConfigMapKeySelector>("configMapKeyRef", ConfigMapKeyRef);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.ObjectFieldSelector>("fieldRef", FieldRef);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.ResourceFieldSelector>("resourceFieldRef", ResourceFieldRef);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.SecretKeySelector>("secretKeyRef", SecretKeyRef);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
