// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NexusAlgorithmSpec : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The args property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Args { get; set; }
#nullable restore
#else
        public List<string> Args { get; set; }
#endif
        /// <summary>The command property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Command { get; set; }
#nullable restore
#else
        public string Command { get; set; }
#endif
        /// <summary>The computeResources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources? ComputeResources { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources ComputeResources { get; set; }
#endif
        /// <summary>The container property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmContainer? Container { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmContainer Container { get; set; }
#endif
        /// <summary>The datadogIntegrationSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusDatadogIntegrationSettings? DatadogIntegrationSettings { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusDatadogIntegrationSettings DatadogIntegrationSettings { get; set; }
#endif
        /// <summary>The errorHandlingBehaviour property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusErrorHandlingBehaviour? ErrorHandlingBehaviour { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusErrorHandlingBehaviour ErrorHandlingBehaviour { get; set; }
#endif
        /// <summary>The runtimeEnvironment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment? RuntimeEnvironment { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment RuntimeEnvironment { get; set; }
#endif
        /// <summary>The workgroupRef property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmWorkgroupRef? WorkgroupRef { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmWorkgroupRef WorkgroupRef { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec"/> and sets the default values.
        /// </summary>
        public NexusAlgorithmSpec()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.V1.NexusAlgorithmSpec();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "args", n => { Args = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "command", n => { Command = n.GetStringValue(); } },
                { "computeResources", n => { ComputeResources = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources.CreateFromDiscriminatorValue); } },
                { "container", n => { Container = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmContainer>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmContainer.CreateFromDiscriminatorValue); } },
                { "datadogIntegrationSettings", n => { DatadogIntegrationSettings = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusDatadogIntegrationSettings>(global::KiotaPosts.Client.Models.V1.NexusDatadogIntegrationSettings.CreateFromDiscriminatorValue); } },
                { "errorHandlingBehaviour", n => { ErrorHandlingBehaviour = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusErrorHandlingBehaviour>(global::KiotaPosts.Client.Models.V1.NexusErrorHandlingBehaviour.CreateFromDiscriminatorValue); } },
                { "runtimeEnvironment", n => { RuntimeEnvironment = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment.CreateFromDiscriminatorValue); } },
                { "workgroupRef", n => { WorkgroupRef = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmWorkgroupRef>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmWorkgroupRef.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("args", Args);
            writer.WriteStringValue("command", Command);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources>("computeResources", ComputeResources);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmContainer>("container", Container);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusDatadogIntegrationSettings>("datadogIntegrationSettings", DatadogIntegrationSettings);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusErrorHandlingBehaviour>("errorHandlingBehaviour", ErrorHandlingBehaviour);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment>("runtimeEnvironment", RuntimeEnvironment);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmWorkgroupRef>("workgroupRef", WorkgroupRef);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
