// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NexusAlgorithmRuntimeEnvironment : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The annotations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment_annotations? Annotations { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment_annotations Annotations { get; set; }
#endif
        /// <summary>The deadlineSeconds property</summary>
        public int? DeadlineSeconds { get; set; }
        /// <summary>The environmentVariables property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KiotaPosts.Client.Models.V1.EnvVar>? EnvironmentVariables { get; set; }
#nullable restore
#else
        public List<global::KiotaPosts.Client.Models.V1.EnvVar> EnvironmentVariables { get; set; }
#endif
        /// <summary>The mappedEnvironmentVariables property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KiotaPosts.Client.Models.V1.EnvFromSource>? MappedEnvironmentVariables { get; set; }
#nullable restore
#else
        public List<global::KiotaPosts.Client.Models.V1.EnvFromSource> MappedEnvironmentVariables { get; set; }
#endif
        /// <summary>The maximumRetries property</summary>
        public int? MaximumRetries { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment"/> and sets the default values.
        /// </summary>
        public NexusAlgorithmRuntimeEnvironment()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment_annotations>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment_annotations.CreateFromDiscriminatorValue); } },
                { "deadlineSeconds", n => { DeadlineSeconds = n.GetIntValue(); } },
                { "environmentVariables", n => { EnvironmentVariables = n.GetCollectionOfObjectValues<global::KiotaPosts.Client.Models.V1.EnvVar>(global::KiotaPosts.Client.Models.V1.EnvVar.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mappedEnvironmentVariables", n => { MappedEnvironmentVariables = n.GetCollectionOfObjectValues<global::KiotaPosts.Client.Models.V1.EnvFromSource>(global::KiotaPosts.Client.Models.V1.EnvFromSource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "maximumRetries", n => { MaximumRetries = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmRuntimeEnvironment_annotations>("annotations", Annotations);
            writer.WriteIntValue("deadlineSeconds", DeadlineSeconds);
            writer.WriteCollectionOfObjectValues<global::KiotaPosts.Client.Models.V1.EnvVar>("environmentVariables", EnvironmentVariables);
            writer.WriteCollectionOfObjectValues<global::KiotaPosts.Client.Models.V1.EnvFromSource>("mappedEnvironmentVariables", MappedEnvironmentVariables);
            writer.WriteIntValue("maximumRetries", MaximumRetries);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
