// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KiotaPosts.Client.Models.V1
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NexusAlgorithmResources : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cpuLimit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CpuLimit { get; set; }
#nullable restore
#else
        public string CpuLimit { get; set; }
#endif
        /// <summary>The customResources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources_customResources? CustomResources { get; set; }
#nullable restore
#else
        public global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources_customResources CustomResources { get; set; }
#endif
        /// <summary>The memoryLimit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemoryLimit { get; set; }
#nullable restore
#else
        public string MemoryLimit { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources"/> and sets the default values.
        /// </summary>
        public NexusAlgorithmResources()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cpuLimit", n => { CpuLimit = n.GetStringValue(); } },
                { "customResources", n => { CustomResources = n.GetObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources_customResources>(global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources_customResources.CreateFromDiscriminatorValue); } },
                { "memoryLimit", n => { MemoryLimit = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cpuLimit", CpuLimit);
            writer.WriteObjectValue<global::KiotaPosts.Client.Models.V1.NexusAlgorithmResources_customResources>("customResources", CustomResources);
            writer.WriteStringValue("memoryLimit", MemoryLimit);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
